# IP and port for BPS REST API
RESTAPI:
  host: 0.0.0.0
  port: 8080

# Number of threads for processing invoices.
BPS:
  threadsForInvoiceObserver: 2

# Frequency of updating the status of invoices in milliseconds.
invoiceProcessor:
  frequency: 5000

# Frequency of updating the status of payments in milliseconds.
paymentProcessor:
  frequency: 3000

# Frequency of updating the status of deposit accounts in milliseconds.
depositAccountProcessor:
  frequency: 5000

# Parameters for the configuration of working with the database.
database:
  connectionURL: "jdbc:postgresql://localhost:12346/db"
  driver: "org.postgresql.Driver"
  maximumPoolSize: 5

# Enabled currencies
# Supported —Åurrencies: BTC, XRP, TRX, GRM
# Set the necessary cryptocurrencies to work with them.
enabledCurrencies:
  coins:
    - GRM

# Example values
BTC:
  coin:
    user: "user"
    password: "password"
    confirmations: 1
  connection:
    host: "127.0.0.1"
    port: "18443"
  explorer:
    frequency: 5000

# Example values
TRX:
  coin:
    # Base58Checksum representation of account
    account: "TW4hF7TVhme1STRC2NToDA41RxCx1H2HbS"
    accountAddress: "41dc6c2bc46639e5371fe99e002858754604cf5847"
    privateKey: "92f451c194301b4a1eae3a818cc181e1a319656dcdf6760cdbe35c54b05bb3ec"
    confirmations: 19
  connection:
    host: "127.0.0.1"
    port: "18190"
  explorer:
    frequency: 3000

# Example values
XRP:
  coin:
    account: "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh"
    privateKey: "snoPBrXtMeMyMHUVTgbuqAfg1SUTb"
    passPhrase: "masterpassphrase"
  connection:
    host: "127.0.0.1"
    port: "51234"
  explorer:
    frequency: 5000

# Example values
GRM:
  coin:
    accountAddress: "kQCBFvmeIOjrZlSoxIVys2nE7nQUxUPM370tbmyC_lzlaIlk"
    privateKey: "5B07270646EED42ABF623E8E971D01A561863BBB85A1DB67FAC9C74E4CB1064E"
    localPassword: "local_password"
    # paymentQueryTimeLimit should be in 0..300
    paymentQueryTimeLimit: 10
    # lengthTagInBytes should be no more than 50
    lengthTagInBytes: 20
  connection:
    # absolute path
    pathToTonClientConfig: "path_to_client_config"
    # absolute path
    keyStorePath: "path_to_keystore"
    # logVerbosityLevel in 1..5
    logVerbosityLevel: 1
  explorer:
    frequency: 5000