BPS:
  threadsForInvoiceObserver: 2

invoiceProcessor:
  frequency: 5000

paymentProcessor:
  frequency: 3000

database:
  connectionURL: "jdbc:h2:~/db"
  driver: "org.h2.Driver"
  maximumPoolSize: 5

# Enabled currencies
# Supported —Åurrencies: BTC, XRP, TRX
enabledCurrencies:
  coins:
    - BTC
    - XRP
    - TRX
    - GRM
    - ETH

# Example values
BTC:
  coin:
    user: "user"
    password: "password"
    confirmations: 1
  connection:
    host: "127.0.0.1"
    port: "18443"
  explorer:
    frequency: 5000

TRX:
  coin:
    # Base58Checksum representation of account
    account: "TW4hF7TVhme1STRC2NToDA41RxCx1H2HbS"
    accountAddress: "41dc6c2bc46639e5371fe99e002858754604cf5847"
    privateKey: "92f451c194301b4a1eae3a818cc181e1a319656dcdf6760cdbe35c54b05bb3ec"
    confirmations: 19
  connection:
    host: "127.0.0.1"
    port: "18190"
  explorer:
    frequency: 3000

XRP:
  coin:
    account: "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh"
    privateKey: "snoPBrXtMeMyMHUVTgbuqAfg1SUTb"
    passPhrase: "masterpassphrase"
  connection:
    host: "127.0.0.1"
    port: "51234"
  explorer:
    frequency: 5000

GRM:
  coin:
    accountAddress: "kQCBFvmeIOjrZlSoxIVys2nE7nQUxUPM370tbmyC_lzlaIlk"
    privateKey: "5B07270646EED42ABF623E8E971D01A561863BBB85A1DB67FAC9C74E4CB1064E"
    localPassword: "local_password"
    # paymentQueryTimeLimit should be in 0..300
    paymentQueryTimeLimit: 10
    # lengthTagInBytes should be no more than 50
    lengthTagInBytes: 20
  connection:
    pathToTonClientConfig: "src/main/resources/TonClientConfig.json"
    keyStorePath: "src/main/resources/TonKeyStore/"
    logVerbosityLevel: 4
  explorer:
    frequency: 5000

ETH:
  coin:
    accountAddress: "0x073cfa4b6635b1a1b96f6363a9e499a8076b6107"
    pathToWallet: "./src/test/resources/ETH/aliceWallet/UTC--2020-03-04T08-33-21.065924100Z--073cfa4b6635b1a1b96f6363a9e499a8076b6107"
    password: "password1"
    confirmations: 2
    defaultPasswordForNewAddresses: "newPassword"
    walletsDir: "./src/test/resources/ETH/aliceWallet/"
    scanningCount: 30
  connection:
    host: "127.0.0.1"
    port: "8545"
  explorer:
    frequency: 5000