GET http://localhost:8080/getBalance/GRM

###

GET http://localhost:8080/getPayment/{payment_id}

###

GET http://localhost:8080/getInvoice/{invoice_id}

###

POST http://localhost:8080/createInvoice
Content-Type: application/json

{
  "currency": "GRM",
  "amount": "1"
}

###

POST http://localhost:8080/sendPayment
Content-Type: application/json

{
  "currency": "GRM",
  "amount": "1",
  "address": "kQCBFvmeIOjrZlSoxIVys2nE7nQUxUPM370tbmyC_lzlaIlk",
  "tag": "TEST"
}
